services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresdb
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: marko
      POSTGRES_PASSWORD: 2323
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U marko -d portfoliodb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: app
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfoliodb
      SPRING_DATASOURCE_USERNAME: marko
      SPRING_DATASOURCE_PASSWORD: 2323
    depends_on:
      postgres:
        condition: service_healthy

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "80:80"    # HTTP (Automatic redirect to HTTPS)
      - "443:443"  # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data     # Stores Let's Encrypt certificates
      - caddy_config:/config # Stores Caddy state configuration
    depends_on:
      - app

volumes:
  postgres_data:
  caddy_data:
  caddy_config: